### ISSUE TITLE
Bar angle from pattern.find_barangle (bar instance from print_eof_barfile) != bar angle from pattern.bar_fourier_compute

### ISSUE THREAD

**Issue by CarrieFilion** [michael-petersen/exptool#21]
At a given time step, the bar angle retrieved from pattern.find_barangle() is not the same as that found by running pattern.bar_fourier_compute(). Sample work flow below. Ex - at time index 556 in the simulation I'm looking at,  pattern.find_barangle() gives 69.28 and pattern.bar_fourier_compute() gives ~1.4 (exact value depends on the chosen values for minr and maxr).

For find_barangle():
```
EOF2Dict = eof.read_binary_eof_coefficients_dict('sim_directory/outcoef.star.run2Fb')
DCp = eof.calculate_eof_phase(EOF2Dict)
eof.print_eof_barfile(DCp,simulation_directory='sim_directory/',\
                        simulation_name='2Fb',morder=2,norder=0)
BarInstance = pattern.BarDetermine()
BarInstance.read_bar('sim_directory/2Fb_m2n0_barpos.dat')
''' BarInstance.unwrap_bar_position()  - have tried with and without unwrapping'''
pattern.find_barangle(BarInstance.time[556], BarInstance, interpolate=False) #interpolate = True gives NaN, which seems to be a separate issue, but here I am giving an exact time in the simulation so no interpolation should be needed
```

For bar_fourier_compute():
```
file = psp_io.Input('sim_directory/OUT.run2Fb.00556',comp='star')
bangle = bar_fourier_compute(file.data['x'],file.data['y']) #have set various rmin, rmax
```

**Comment by michael-petersen** [comment]
Okay, I think we're fighting multiple issues here:
0. I agree that there isn't always a clear reason that `find_barangle` and `bar_fourier_compute` are used, and interchangeably. In general, I default to `find_barangle` from the coefficients, but as you note, it has some inherent problems (see #2 below).
1. `find_barangle` is definitely in radians, but it doesn't (by default) wrap to within [0,2pi], instead counting on (say) cos(pi) = cos(3pi). This could be wrapped for some easier agreement.
2. The n=0 basis function may well be perpendicular to the bar if the spiral is sufficiently strong. I usually default to n=2 -- I will change the default in the code. You can try regenerating the bar file with n=1 or n=2 and see what happens.
3. It is completely possible that this bar rotates counterclockwise, instead of (the 'usual') clockwise, in which case I was too sloppy in adding a `-1`. That was solely intended to get the direction of travel right (i.e. increasing or decreasing theta, depending on the rotation sense). At other places in the code I try to check; this is unfortunately not one of them. I'll take a look at this again.

**Comment by michael-petersen** [comment]
I think this is fixed by your recent pull request? If not, let's re-open a new updated issue.
